### ISSUE TITLE
Missing Rel operation

### ISSUE THREAD

**Issue by pajatopmr** [fxnn/gopath#1]
As near as I can tell via a grep and browsing the documentation, the Rel() operation is missing.  Very nice package.  Well worth adding tests and ensuring that the snippet in the readme.md file compiles and runs correctly.  I would like to see this in the standard library.

**Comment by fxnn** [comment]
I really forgot that. How embarrassing, sorry for that.

@pajatopmr: Thank you for not trusting me here :) Also thank you for your feedback!
